$schema: "http://json-schema.org/draft-07/schema#"
type: "object"
properties:
  name:
    type: "string"
  version:
    type: "string"
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  description:
    type: "string"
  settings:
    type: "object"
    properties:
      enabled:
        type: "boolean"
      count:
        type: "integer"
        minimum: 0
    required:
      - "enabled"
required:
  - "name"
  - "version"
additionalProperties: false
